substitutions:
  _API_URL: ""
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/web/Dockerfile'
      # This tag matches your new deploy command
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/swiftspeak/swiftspeak-web:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_API_URL}'
      - '.'
images:
  # This tag matches your new deploy command
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/swiftspeak/swiftspeak-web:latest'