steps:
  # Enable corepack to use pnpm
  - name: 'node:20'
    entrypoint: 'corepack'
    args: ['enable']
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npx'
    args: ['pnpm', 'install']
  # Build the entire workspace
  - name: 'node:20'
    entrypoint: 'npx'
    args: ['pnpm', 'build']
  # Build the api image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/$PROJECT_ID/swiftspeak/swiftspeak-api:latest
      - -f
      - Dockerfile.api.standalone
      - .
images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/swiftspeak/swiftspeak-api:latest
