steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/swift123/swiftspeak/swiftspeak-api:latest
      - -f
      - Dockerfile.api.standalone
      - .
images:
  - us-central1-docker.pkg.dev/swift123/swiftspeak/swiftspeak-api:latest
